
/**
 * Menu actions
 */

export const TRIGGER_TOGGLE = 'TRIGGER_TOGGLE';
export const TOP_BAR_FOCUS_INDEX = 'TOP_BAR_FOCUS_INDEX';
export const FORCE_TOP_BAR_FOCUS_INDEX = 'FORCE_TOP_BAR_FOCUS_INDEX';
export const UNSUPPRESS_TOP_BAR_FOCUS = 'UNSUPPRESS_TOP_BAR_FOCUS';
export const TOP_BAR_ITEM_IDENTIFY = 'TOP_BAR_ITEM_IDENTIFY';
export const SIDE_BAR_FOCUS_INDEX = 'SIDE_BAR_FOCUS_INDEX';
export const SIDE_BAR_ITEM_IDENTIFY = 'SIDE_BAR_MENU_ITEM_IDENTIFY';
export const SIDE_BAR_TRIGGER_IDENTIFY = 'SIDE_BAR_TRIGGER_IDENTIFY';

/**
 * Viewport actions
 */

export const VIEWPORT_SIZE_CHANGE = 'VIEWPORT_SIZE_CHANGE';
